# -*- coding: utf-8 -*-
"""GAN 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uCxCEIH8C05uNhPXJFF8Rt97aiSOM1z
"""

NIHAR KOCHE, Roll no.34 Sec:- B

!pip install kagglehub

import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
import os, cv2, kagglehub, time

# 2. LOAD DATASET
path = kagglehub.dataset_download("paultimothymooney/blood-cells")

IMG_SIZE = 64
DATASET_PATH = os.path.join(path, "dataset2-master", "dataset2-master", "images", "TRAIN")

images = []

for class_name in os.listdir(DATASET_PATH):
    folder = os.path.join(DATASET_PATH, class_name)

    if not os.path.isdir(folder):
        continue

    for img_name in os.listdir(folder)[:1000]:
        img = cv2.imread(os.path.join(folder, img_name))
        if img is None:
            continue

        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
        images.append(img)

images = np.array(images, dtype=np.float32)
images = images / 127.5 - 1.0

print("Dataset shape:", images.shape)

BATCH_SIZE = 32
dataset = tf.data.Dataset.from_tensor_slices(images).shuffle(1000).batch(BATCH_SIZE)

# Show Sample Images
plt.figure(figsize=(6,6))
for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow((images[i]+1)/2)
    plt.axis("off")
plt.show()

# Generator Model
def build_generator():
    model = tf.keras.Sequential([
        layers.Dense(8*8*256, use_bias=False, input_shape=(100,)),
        layers.BatchNormalization(),
        layers.LeakyReLU(),

        layers.Reshape((8,8,256)),

        layers.Conv2DTranspose(128, 5, strides=2, padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.LeakyReLU(),

        layers.Conv2DTranspose(64, 5, strides=2, padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.LeakyReLU(),

        layers.Conv2DTranspose(3, 5, strides=2, padding='same',
                               use_bias=False, activation='tanh')
    ])
    return model

# Discriminator Model
def build_discriminator():
    model = tf.keras.Sequential([
        layers.Conv2D(64, 5, strides=2, padding='same', input_shape=(64,64,3)),
        layers.LeakyReLU(),
        layers.Dropout(0.3),

        layers.Conv2D(128, 5, strides=2, padding='same'),
        layers.LeakyReLU(),
        layers.Dropout(0.3),

        layers.Flatten(),
        layers.Dense(1)
    ])
    return model

generator = build_generator()
discriminator = build_discriminator()

_ = generator(tf.random.normal([1,100]))
_ = discriminator(tf.random.normal([1,64,64,3]))

# Loss + Optimizer
loss_fn = tf.keras.losses.BinaryCrossentropy(from_logits=True)

gen_optimizer = tf.keras.optimizers.Adam(2e-4)
disc_optimizer = tf.keras.optimizers.Adam(5e-5)

# Loss Functions And Accuracy Function
def generator_loss(fake_output):
    return loss_fn(tf.ones_like(fake_output), fake_output)

def discriminator_loss(real_output, fake_output):
    real_labels = tf.ones_like(real_output) * 0.9   # 🔥 smoothing
    fake_labels = tf.zeros_like(fake_output)

    real_loss = loss_fn(real_labels, real_output)
    fake_loss = loss_fn(fake_labels, fake_output)

    return real_loss + fake_loss

def discriminator_accuracy(real_output, fake_output):
    real = tf.sigmoid(real_output)
    fake = tf.sigmoid(fake_output)

    real_acc = tf.reduce_mean(tf.cast(real > 0.5, tf.float32))
    fake_acc = tf.reduce_mean(tf.cast(fake < 0.5, tf.float32))

    return (real_acc + fake_acc) / 2

def generator_accuracy(fake_output):
    fake = tf.sigmoid(fake_output)
    return tf.reduce_mean(tf.cast(fake > 0.5, tf.float32))

# Training Step
@tf.function
def train_step(images):

    batch_size = tf.shape(images)[0]

    noise = tf.random.normal([batch_size, noise_dim])

    with tf.GradientTape() as disc_tape:

        fake_images = generator(noise, training=True)

        real_output = discriminator(images, training=True)
        fake_output = discriminator(fake_images, training=True)

        d_loss = discriminator_loss(real_output, fake_output)

    grads_d = disc_tape.gradient(d_loss, discriminator.trainable_variables)
    disc_optimizer.apply_gradients(zip(grads_d, discriminator.trainable_variables))

    for _ in range(2):

        noise = tf.random.normal([batch_size, noise_dim])

        with tf.GradientTape() as gen_tape:

            fake_images = generator(noise, training=True)
            fake_output = discriminator(fake_images, training=True)

            g_loss = generator_loss(fake_output)

        grads_g = gen_tape.gradient(g_loss, generator.trainable_variables)
        gen_optimizer.apply_gradients(zip(grads_g, generator.trainable_variables))

    d_acc = discriminator_accuracy(real_output, fake_output)
    g_acc = generator_accuracy(fake_output)

    return g_loss, d_loss, g_acc, d_acc

# Training Loop
EPOCHS = 200

for epoch in range(EPOCHS):

    for batch in dataset:
        g_loss, d_loss, g_acc, d_acc = train_step(batch)

    print(f"Epoch {epoch+1}/{EPOCHS} | "
          f"D Loss: {d_loss:.4f} | G Loss: {g_loss:.4f} | "
          f"D Acc: {d_acc:.4f} | G Acc: {g_acc:.4f}")

def evaluate_model(generator, discriminator, dataset):

    real_acc_list = []
    fake_acc_list = []

    for real_images in dataset.take(10):  # check few batches

        batch_size = tf.shape(real_images)[0]
        noise = tf.random.normal([batch_size, 100])

        fake_images = generator(noise, training=False)

        real_output = discriminator(real_images, training=False)
        fake_output = discriminator(fake_images, training=False)

        # Convert to probability
        real_pred = tf.sigmoid(real_output)
        fake_pred = tf.sigmoid(fake_output)

        # Accuracy
        real_acc = tf.reduce_mean(tf.cast(real_pred > 0.5, tf.float32))
        fake_acc = tf.reduce_mean(tf.cast(fake_pred < 0.5, tf.float32))

        real_acc_list.append(real_acc)
        fake_acc_list.append(fake_acc)

    print("\nEvaluation Results:")
    print(f"Real Accuracy: {tf.reduce_mean(real_acc_list):.4f}")
    print(f"Fake Accuracy: {tf.reduce_mean(fake_acc_list):.4f}")


# 🔹 Show final images
print("\nFinal Generated Images:")
generate_images(generator)

# 🔹 Print evaluation AFTER images
evaluate_model(generator, discriminator, dataset)